### ISSUE TITLE
Is it better to use try expressions?

### ISSUE THREAD

**Issue by mantou132** [tc39/proposal-private-fields-in-in#9]
https://github.com/isiahmeadows/proposal-try-expression

try expression is a more general method.

**Comment by ljharb** [comment]
Indeed, that is more general, but i think `in` makes sense for private fields regardless, and i don’t think it’d be more ergonomic to have to use a try expression and then inspect the error.

It was certainly considered, though: https://github.com/tc39/proposal-private-fields-in-in#try-statement

Would you be interested in making a PR to the readme to add this proposal as an example?

**Comment by ljharb** [comment]
This proposal [reached stage 3](https://twitter.com/ljharb/status/1354517237340618754) at today's TC39.
